### ISSUE TITLE
Shipping API: How does Shipper correlate with ReturnService?

### ISSUE THREAD

**Issue by brendonparker** [UPS-API/api-documentation#1]
Not strictly an documentation/spec issue, but perhaps some clarity could help...

When creating a return shipment, and specifing the `ReturnService` element, should the `Shipper` element be the same as it was on the original shipment, or should it reflect the returner's address? I assume it should use the same UPS account.

**Comment by rcmasey** [comment]
The Shipper address should always be the address of the client creating the shipment. 
The Ship From address should be the returner's address.
