### ISSUE TITLE
Tracking API returns status 200 response for "Tracking Information Not Found"

### ISSUE THREAD

**Issue by ataylorkato** [UPS-API/api-documentation#102]
Per the documentation, a 401 status response would be expected to be returned from the Tracking API in the event that tracking information was not found. However, the Tracking API seems to return a 200 status response instead.

Request URL:

`https://onlinetools.ups.com/api/track/v1/details/1Z5629230309413682?locale=en_US&returnSignature=true&returnPOD=true`

Response:

```
{
    "trackResponse": {
        "shipment": [
            {
                "inquiryNumber": "1Z5629230309413682",
                "warnings": [
                    {
                        "code": "TW0001",
                        "message": "Tracking Information Not Found"
                    }
                ]
            }
        ]
    }
}
```
![image](https://github.com/UPS-API/api-documentation/assets/903291/b186ffc6-74bf-496c-b3ea-66ef47f8860f)

**Comment by UPSRahul** [comment]
Hi, the Track API documentation pushed on 4/4/24 does not list a 401 response.

**Comment by ataylorkato** [comment]
My apologies - I meant a 404 response, which IS listed in the documentation:

![image](https://github.com/UPS-API/api-documentation/assets/903291/b41591eb-f610-4716-987e-e246a35dffb9)
