### ISSUE TITLE
Ship API - Including DeliveryConfirmation.DCISType results in Bad Request

### ISSUE THREAD

**Issue by jkerrwilson** [UPS-API/api-documentation#107]
Seemingly no matter what value is provided, I am unable to set a signature required option when creating a shipment. The API (both integration and production) consistently returns 400, indicating that the service is not available between the given source and destination addresses.

I have tested this with several valid US to US addresses to no avail.

**Comment by UPSRahul** [comment]
Hi, please reach out to the UPS Help Desk for more assistance. UPS Help Desk: https://developer.ups.com/contactus
