### ISSUE TITLE
Residential vs ResidentialAddressIndicator

### ISSUE THREAD

**Issue by mxmissile** [UPS-API/api-documentation#109]
Request sample is showing an optional `ShipTo.Residential` indicator, also `ShipTo.Address` has a `ResidentialAddressIndicator` indicator. So which one do we use? Why is there two options?

<img width="247" alt="image" src="https://github.com/UPS-API/api-documentation/assets/235144/5c7652d1-2f44-4665-8ddc-a54b210265cf">
<img width="565" alt="image" src="https://github.com/UPS-API/api-documentation/assets/235144/c10dc588-8cf1-4682-8730-812063f74562">

**Comment by UPSRahul** [comment]
Hi, we will update the API specification based on the feedback. Please use the ResidentialAddressIndicator.
