### ISSUE TITLE
Tracking API endpoint missing content-type for all responses

### ISSUE THREAD

**Issue by elidrissidev** [UPS-API/api-documentation#11]
Tracking API endpoint is missing a proper content-type for all the possible responses, currently it's set to `*/*`, it should be `application/json` instead.

**Comment by chuntoulee** [comment]
Thank you for bringing this concern to our attention.  Our technical team is looking into it and will provide a more substantive response shortly.

**Comment by UPSRahulBhatnagar** [comment]
Hi, thank you for your comment. We have updated the tracking documentation on the developer portal and merged the code in this repository.
