### ISSUE TITLE
Configuration for using default payment method on users UPS account

### ISSUE THREAD

**Issue by jareko999** [UPS-API/api-documentation#114]
Our software allows users to connect their UPS accounts and print labels through our app. What I'm not clear on, is how to use the default payment method under their UPS account to purchase labels. I noticed

```
PaymentInformation: {
     ShipmentCharge: {
        Type: '01',
        BillShipper: { AccountNumber: accountNumber },
     },
},
```

But am I considered the Shipper in our use case? If they're the "Shipper", I didn't see a way to access the 6 digit account number, only our own in the Developer app settings, which is why I assumed we were the "Shipper". I just want to know what the configuration is for having our users use their connected UPS accounts to pay for labels, pickups, etc.

**Comment by jareko999** [comment]
@UPSRahul Any advice here would be greatly appreciated.

**Comment by jareko999** [comment]
Or @UPSCadeCreech? May seem like a dumb question, but I guess I'm unclear on the purpose of OAuth'ing with UPS if you can't use the connected accounts own default payment method to purchase labels.

**Comment by UPSRahul** [comment]
Hi, your users will need to enter their UPS credentials into your system and your system needs to use the AuthCode flow. This will allow your users to be the shipper and authorized user.

**Comment by jareko999** [comment]
Credentials meaning their account number, correct? That’s required during a shipmentrequest, but we can’t get that during authentication. So they just add it manually. Not ideal but it works. I’m guessing the account number must be tied to the access token in some way? Otherwise anyone could use the account number?
  
  
  
  
  
  
  

  
  
>
