### ISSUE TITLE
Missing or Invalid account number for Payment Details

### ISSUE THREAD

**Issue by huffmanr** [UPS-API/api-documentation#115]
Error is incorrect.

We're getting the above Error "Missing or Invalid account number for Payment Details"
When sending a Rate Request to https://onlinetools.ups.com/api/rating/v2403/Ratetimeintransit
(Shipper Number Redacted)

`{
  "RateRequest": {
    "Request": {
      "TransactionReference": {
        "CustomerContext": "CustomerContext"
      }
    },
    "Shipment": {
      "Shipper": {
        "Name": "ProShip",
        "ShipperNumber": "xxxxxx",
        "Address": {
          "AddressLine": [
            "311 S. Wacker Drive"
          ],
          "City": "CHICAGO",
          "StateProvinceCode": "IL",
          "PostalCode": "60606",
          "CountryCode": "US"
        }
      },
      "ShipTo": {
        "Name": "Do Not Ship",
        "Address": {
          "AddressLine": [
            "20725 SE 162ND AVE"
          ],
          "City": "LOCHLOOSA",
          "StateProvinceCode": "FL",
          "PostalCode": "32662",
          "CountryCode": "US"
        }
      },
      "ShipFrom": {
        "Name": "ProShip",
        "Address": {
          "AddressLine": [
            "311 S. Wacker Drive"
          ],
          "City": "CHICAGO",
          "StateProvinceCode": "IL",
          "PostalCode": "60606",
          "CountryCode": "US"
        }
      },
      "PaymentDetails": {
        "ShipmentCharge": {
          "Type": "01",
          "BillShipper": {
            "AccountNumber": "xxxxxx"
          }
        }
      },
      "Service": {
        "Code": "02"
      },
      "NumOfPieces": "1",
      "Package": {
        "SimpleRate": {
          "Description": "SimpleRateDescription",
          "Code": "XS"
        },
        "PackagingType": {
          "Code": "02",
          "Description": "Packaging"
        },
        "Dimensions": {
          "UnitOfMeasurement": {
            "Code": "IN",
            "Description": "Inches"
          },
          "Length": "5",
          "Width": "5",
          "Height": "5"
        },
        "PackageWeight": {
          "UnitOfMeasurement": {
            "Code": "LBS",
            "Description": "Pounds"
          },
          "Weight": "1"
        }
      },
	  "DeliveryTimeInformation": {
          "PackageBillType": "03",
          "Pickup": {
            "Date": "20240517",
            "Time": "1000"
          }
        }
    }
  }
}`

But the thing is We only get it when we Request A Token with this code.
`using (HttpClient client = new HttpClient())
{
    var base64String = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{ClientID}:{ClientKey}"));
    client.DefaultRequestHeaders.Add("Authorization", "Basic " + base64String);
    List<KeyValuePair<string, string>> postData = new List<KeyValuePair<string, string>>();
    postData.Add(new KeyValuePair<string, string>("grant_type", "refresh_token"));
    postData.Add(new KeyValuePair<string, string>("refresh_token", RestToken));

    var response = client.PostAsync("https://onlinetools.ups.com/security/v1/oauth/refresh", new FormUrlEncodedContent(postData)).Result;

    if (response.StatusCode == HttpStatusCode.OK)
    {
        var reply = response.Content.ReadAsStringAsync().Result;
        JObject TokenReply = JObject.Parse(reply);
		return TokenReply;
    }
    else
    {
        return null;
    }
}`
We Get a Valid Token Back
`{
    "access_token": "REDACTED",
    "client_id": "REDACTED",
    "expires_in": "14399",
    "issued_at": "1715963311375",
    "refresh_token": "REDACTED",
    "refresh_token_expires_in": "5183999",
    "refresh_token_issued_at": "1715963311375",
    "refresh_token_status": "approved",
    "status": "approved",
    "token_type": "Bearer"
}`

But if we generate a token via Postman POST to https://wwwcie.ups.com/security/v1/oauth/refresh
We also get a Valid Token back but this Access Token 
`{
    "refresh_token_expires_in": "5183999",
    "refresh_token_status": "approved",
    "token_type": "Bearer",
    "issued_at": "1715968039113",
    "client_id": "REDACTED",
    "access_token": "REDACTED",
    "refresh_token": "REDACTED",
    "refresh_token_issued_at": "1715968039113",
    "expires_in": "14399",
    "status": "approved"
}`

Will allow a successful rate request via Postman (Exact same as before)
Only thing we change between the Rate calls is the returned access_token,  nothing else.

Has anyone else seen this behavior?

**Comment by pkuppens** [comment]
@huffmanr,  I think I am looking at something similar, for shipments.

I use the example payload from the documentation and pass it to the wwwcie environment, to get this error:
Hard 9120068 - Either credit card or account number information is needed but not both

Even when I fill in our account number, this is not recognized. it seems the account number doesn't work on wwwcie.

I don't know if there is some general test account number on wwwcie, or that we should ask for our specific test account number.
However, validation on wwwcie seems real.

Do you have some progress already?

**Comment by huffmanr** [comment]
Ok found the issue.
We had 2 accounts we were using for getting our Refresh Tokens.
1 Account fully configured for shipping with valid account numbers ect
1 Account that was just a base account for communication with UPS for QA.
When we request a Refresh token from the first account or second account, the API would issue a "Valid" Refresh Token.
This "Valid" (used loosely) Will grant an Access Token that's "Valid" 
If from the first account e-mail , rate / ship works fine as it has an Account number based on the e-mail / refresh token.
If from the second account e-mail, rate / ship fails for the above error.

In reality the Token Request "Should" fail as it's not a valid account to create tokens with. 

Simple solution Return the User ID in token creation so we know what Account we're trying to process from.
Took level 3 support to find out that the reason for the error is the account getting the initial Refresh token.

**Comment by andrewyin1994** [comment]
> @huffmanr, I think I am looking at something similar, for shipments.
> 
> I use the example payload from the documentation and pass it to the wwwcie environment, to get this error: Hard 9120068 - Either credit card or account number information is needed but not both
> 
> Even when I fill in our account number, this is not recognized. it seems the account number doesn't work on wwwcie.
> 
> I don't know if there is some general test account number on wwwcie, or that we should ask for our specific test account number. However, validation on wwwcie seems real.
> 
> Do you have some progress already?

Might sound dumb but I was having this problem, and it was because I was storing the account number as a number value in my env file instead of string
