### ISSUE TITLE
Wrong and missing error response types

### ISSUE THREAD

**Issue by elidrissidev** [UPS-API/api-documentation#12]
1. For example if you submit an invalid inquiry number to the tracking endpoint you get this JSON response:

```json
{
  "response": {
    "errors": [
      {
        "code": "TV1002",
        "message": "Invalid inquiry number"
      }
    ]
  }
}
```

But in `Tracking.json`, the shape of the response is missing the `response` object that wraps the `errors` array.

2. In some endpoints the error response body is missing. For example 401 response for [void shipment](https://developer.ups.com/api/reference?loc=en_US#operation/VoidShipment).
3. There's also possible HTTP status codes that can be returned by some endpoints that are not mentioned in the specification. The void shipment endpoint has this issue too, it's missing the `400` response when a shipment cannot be voided.

**Comment by chuntoulee** [comment]
Thank you for bringing this concern to our attention.  Our technical team is looking into it and will provide a more substantive response shortly.

**Comment by UPSRahulBhatnagar** [comment]
Hi, thank you for your comment. We have updated the tracking documentation on the developer portal and merged the code in this repository.
