### ISSUE TITLE
GuaranteedDelivery object isn't in Rating.yaml but is returned by UPS servers

### ISSUE THREAD

**Issue by HH-RSmith** [UPS-API/api-documentation#124]
GuaranteedDelivery should be a property in RatedShipment object.

**Location:**
RATEResponseWrapper / RateResponse / RatedShipment 

GuaranteedDelivery is shown in Rating Package RESTful Developer Guide.pdf.

**URL used:**
https://wwwcie.ups.com/api/rating/v2403/Shop

**Response from UPS Server:**
...
"GuaranteedDelivery": {
	"BusinessDaysInTransit": "1",
	"DeliveryByTime": "10:30 A.M."
}
...

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
