### ISSUE TITLE
Rating Service Description Blank

### ISSUE THREAD

**Issue by kabutotx** [UPS-API/api-documentation#13]
For a "SHOP" request option, the Service Code numbers are there but the Description is blank. Can we add the correct Service Code Description for each service code so I don't have to make a lookup table?

**Comment by DemigodCode** [comment]
Any news or reaction on this? The old SOAP-API returned the service names, so why is it disabled here?

**Comment by UPSRahulBhatnagar** [comment]
Hi, thank you for raising this issue. Currently neither version of the API returns the description with the "SHOP" option. One method for obtaining the service name is to use "Shoptimeintransit" request option. The description will be returned in the "RatedShipment.TimeInTransit.ServiceSummary.Service.Description" field. An alternative is to use the following appendix: https://developer.ups.com/api/reference/rating/appendix?loc=en_US

**Comment by xerc** [comment]
in the DOC it is defined that "there will be always a description"!
https://github.com/UPS-API/api-documentation/blob/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L133-L135

**Comment by xerc** [comment]
TESTed @ rating/v2403/shoptimeintransit
```php
    ["Service"]=>
    object(stdClass)#527 (2) {
      ["Code"]=>
      string(2) "54"
      ["Description"]=>
      string(0) ""
    }
    ["TimeInTransit"]=>
    object(stdClass)#561 (5) {
      ["ServiceSummary"]=>
      object(stdClass)#563 (4) {
        ["Service"]=>
        object(stdClass)#562 (1) {
          ["Description"]=>
          string(16) "UPS Express Plus"
        }
```
