### ISSUE TITLE
Label Recovery returns GIF for COD Shipments instead ZPL and EPL

### ISSUE THREAD

**Issue by riepa** [UPS-API/api-documentation#130]
When the shipment is not COD I can get label in ZPL and EPL format. When it's COD when I pick ZPL or EPL format it returns GIF.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. In order to investigate this, we require more information. Please reach out to the UPS Help Desk via the information here: https://developer.ups.com/contactus.
