### ISSUE TITLE
RateRequest - Shipment_Service - Code minLength

### ISSUE THREAD

**Issue by dylandrush** [UPS-API/api-documentation#136]
The minLength is set to 3 when the only valid values have a length of 2.

https://github.com/UPS-API/api-documentation/blob/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L2643C1-L2643C23

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
