### ISSUE TITLE
Rating - Package_PackageWeight - Weight minLength

### ISSUE THREAD

**Issue by dylandrush** [UPS-API/api-documentation#137]
The minLength for weight is set to 6.  Is the value expected to be padded with 0's?  if the weight for example was 12.3 LBS would I really need to set this to be 12.300 or is this minLength incorrect?

https://github.com/UPS-API/api-documentation/blame/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L2896

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
