### ISSUE TITLE
RatedShipment_Service Incorrect Code and Description Lengths

### ISSUE THREAD

**Issue by dylandrush** [UPS-API/api-documentation#139]
The minLength of 3 for the code is wrong.  It should be 2. 

Sometimes empty strings are returned for the Description so a minLength of 1 is invalid.

https://github.com/UPS-API/api-documentation/blob/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L4520-L4540

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
