### ISSUE TITLE
RatedShipment_BillingWeight minLength

### ISSUE THREAD

**Issue by dylandrush** [UPS-API/api-documentation#140]
minLength is set to 5, and UPS returns values that are shorter than 5.

For example:
```json
      "BillingWeight": {
        "UnitOfMeasurement": {
          "Code": "LBS",
          "Description": "Pounds"
        },
        "Weight": "70.0"
      },
```

https://github.com/UPS-API/api-documentation/blob/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L4561-L4578

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
