### ISSUE TITLE
RatedShipment_TransportationCharges - MonetaryValue minLength

### ISSUE THREAD

**Issue by dylandrush** [UPS-API/api-documentation#141]
The minLength is 16, however, returned values are not padded to meet this minLength:
```json
      "TransportationCharges": {
        "CurrencyCode": "USD",
        "MonetaryValue": "160.02"
      },
```

https://github.com/UPS-API/api-documentation/blob/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L4601-L4622

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
