### ISSUE TITLE
RatedShipment_BaseServiceCharge - MonetaryValue - minLength

### ISSUE THREAD

**Issue by dylandrush** [UPS-API/api-documentation#142]
The minLength of 16 is not what is ever returned:
```json
      "BaseServiceCharge": {
        "CurrencyCode": "USD",
        "MonetaryValue": "0.00"
      },
```

https://github.com/UPS-API/api-documentation/blob/4962e982cfca654bee7fbc4c9a0b80105cf480aa/Rating.yaml#L4623-L4647

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have pushed updated OpenAPI specs.
