### ISSUE TITLE
OAuth 2.0 documents

### ISSUE THREAD

**Issue by Lumuy** [UPS-API/api-documentation#145]
Hi, UPS team

   Where is the OAuth 2.0 documents? I can see the alert on UPS official site which remind me to finish auth migration, but I can't find the documents.
    
   https://wwwcie.ups.com/security/v1/oauth/token is the correct url for OAuth 2.0?

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. Here are some of the UPS Developer Portal resources for OAuth 2.0: https://developer.ups.com/get-started & https://developer.ups.com/oauth-developer-guide.
 
Here are the URLs, also available in the OAuth OpenAPI specs:
Customer Integration Environment URL:  https://wwwcie.ups.com/security/v1/oauth/token
Production URL: https://onlinetools.ups.com/security/v1/oauth/token
