### ISSUE TITLE
Shipping API documentation error?  3 address lines print on label, not limited to 2

### ISSUE THREAD

**Issue by nightcoding2021** [UPS-API/api-documentation#146]
The documentation states only first two address lines will print on label.  This limitation caused me no end of problems.  However, I've just tested this and in fact all three printed on label (live environment).

@UPSRahul Please can it be clarified if three lines are supported, and if so please fix the documentation?  

![image](https://github.com/user-attachments/assets/21af3bc2-a4d3-4520-9dd7-578b477db996)

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. If Address lines 1, 2, & 3 are provided, then they will be printed on the label.
