### ISSUE TITLE
How to encode extended ASCII address characters for the API

### ISSUE THREAD

**Issue by nightcoding2021** [UPS-API/api-documentation#148]
As I understand it, JSON uses utf-8 as default and I am encoding in that format.  However I recall that UPS labels via the API only support ASCII characters, and not the extended codes (i.e. positions 128-255) - can that be confirmed it's still the case?

I'm already stripping out / removing diacritics.

Question - How should I be substituing characters such as the ordinal indicator character, e.g.  "Nº15" which prints as "N?15" on the UPS label output.

Thanks!

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. There are a few extended ASCII character sets, which of these character sets would you like to use?

**Comment by nightcoding2021** [comment]
Surely the question is what ASCII character set does the UPS API use?

One example I'm having problems with is printing the Spanish piso abbreviation - degree symbol °  --- That is printing as a question mark on the UPS labels.   I would have thought with UPS operating in Spanish speaking regions, the API should support ° and the others.

Is this correct?  If so, how does UPS want customers to substitute the ° character - with what ASCII, or should it be blanked out?

Thanks!

**Comment by UPSRahul** [comment]
Hi, please reference the UPS Developer Portal's Ship API documentation for the request field "ShipmentRequest.LabelSpecification.CharacterSet". This field lists the available character sets.
