### ISSUE TITLE
ItemizedCharges Codes

### ISSUE THREAD

**Issue by mxmissile** [UPS-API/api-documentation#151]
I'm getting these charges added to a shipment, where are the codes documented?

```
  "ItemizedCharges": [
    {
      "Code": "375",
      "CurrencyCode": "USD",
      "MonetaryValue": "63.00"
    },
    {
      "Code": "377",
      "CurrencyCode": "USD",
      "MonetaryValue": "197.50",
      "SubType": "Commercial"
    }
  ],
```

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. These codes can be found on the UPS Developer Portal Shipping API Appendix 1: https://developer.ups.com/api/reference/shipping/appendix1 under the "Accessorial / Surcharge Codes" section.
