### ISSUE TITLE
How to get the receipts' label?

### ISSUE THREAD

**Issue by pljay** [UPS-API/api-documentation#152]
I searched the latest developer document and found no corresponding attribute. Can you help me point it out? If this file is not provided by UPS-API, can I produce it myself?

**Comment by UPSRahul** [comment]
Hi, we have updated the question to remove any potential PII.

**Comment by pljay** [comment]
> Hi, we have updated the question to remove any potential PII.

How to getUPS COPY files？

**Comment by UPSRahul** [comment]
Hi, please reference the UPS Developer Portal's Ship API documentation for the request container "ShipmentRequest.ReceiptSpecification". This section specifies the receipt and receipt format.
