### ISSUE TITLE
Ship API suddenly returning PackageResults_RateModifier as array instead of object

### ISSUE THREAD

**Issue by kdurkin77** [UPS-API/api-documentation#155]
We have been using version 2403 of the Ship API (the latest as far as I'm aware) and it has been returning PackageResults_RateModifier as an object just as the spec shows it should. I believe something changed over the weekend and now it's suddenly returning an array and has broken our service. The issues with the array vs object were fixed in this version until now.

Additionally, this morning I was seeing this same problem on the sandbox/dev environment (https://wwwcie.ups.com) but then that service went down and when it came back up it was resolved. The same needs done on the production environment (https://onlinetools.ups.com)

**Comment by mxmissile** [comment]
This started for me a month ago. Annoying to say the least.

**Comment by UPSRahul** [comment]
Hi, thank you for the comment. Please reference the UPS Developer Portal's documentation for the Ship API at "ShipmentResponse.ShipmentResults.PackageResults.RateModifier". For versions >=2403, the element will always be returned as an array.

**Comment by kdurkin77** [comment]
Sure, but then the spec needs to match that and it currently does not. See https://github.com/UPS-API/api-documentation/blob/main/Shipping.yaml#L11303 - I had to manually modify this to get it to work, which we should not have to do. Can we please re-open this until the spec matches what's actually happening?

![image](https://github.com/user-attachments/assets/c5d2c11b-008f-4229-9744-4ee116003357)

![image](https://github.com/user-attachments/assets/e02bac08-5262-4d9c-87d8-5e2ea78a77a4)
