### ISSUE TITLE
Wrong property mentioned

### ISSUE THREAD

**Issue by cn42** [UPS-API/api-documentation#22]
At work on this API I found a wrong declared property in the schema.
As mentioned in the [docs](https://developer.ups.com/api/reference?loc=en_US#operation/Shipment!path=ShipmentRequest/Shipment/Package/Dimensions/UnitOfMeasurement/Code&t=request) the property for UnitOfMeasurement should be code but in the schema here it is UnitOfMeasurement. Therefor I am not able to generate the correct API files for my project.

https://github.com/UPS-API/api-documentation/blob/fbc372e321febacf528f4438aaddb40bd5d4b2b5/Shipping.json#L6690

**Comment by UPSRahulBhatnagar** [comment]
Hi, thank you for the feedback. The spec has been updated.
