### ISSUE TITLE
Address Validation - AddressKeyFormat array clarification

### ISSUE THREAD

**Issue by kabutotx** [UPS-API/api-documentation#28]
In address validation request, AddressKeyFormat is an array of objects. Passing AddressKeyFormat as an object or a single object array works fine. If I add a second array object it is ignored. Does address validation only work with 1 AddressKeyFormat object and not multiple? Is it an array for future multiple address objects?

**Comment by UPSRahul** [comment]
Hi, thanks for your comment. At this time, we do not support multiple address objects. The specs have been updated to show that only one object should be passed.
