### ISSUE TITLE
documentation has a lot of problems.

### ISSUE THREAD

**Issue by tplsoft** [UPS-API/api-documentation#31]
First of all your documentations are not clear and have inconsistencies

for example; for Auth 2 v1/oauth/authorize request docs are not matching there are different parameters and not clear what are the possible values or how to get them.

https://developer.ups.com/api/reference/oauth/authorization-code?loc=en_US

https://developer.ups.com/api/reference?loc=en_US#tag/OAuthAuthCode_other
the code in the last example is not correct either; at least needs to read data from header but there is no such a code.

**Comment by UPSRahul** [comment]
Hi, we are closing this since we have not received any additional information. If needed, please create a new GitHub issue.
