### ISSUE TITLE
Schema types with the same name in different APIs but with different fields

### ISSUE THREAD

**Issue by elidrissidev** [UPS-API/api-documentation#34]
Some schema types are defined in multiple API files with the same name, but their fields are different. This can cause conflicts when using codegen tools and leads to missing types. I think types should never share the same name if their definition isn't exactly the same.

Example:

`Shipment_ShipTo` is defined 3 times in `Rating.json`, `Shipping.json`, and `TForceFreightShipping.json`, but all the three definitions have some differences. In my case, the one `TForceFreightShipping.json` was "winning" and it resulted in issues when trying to use the Shipment API.

**Comment by UPSRahul** [comment]
Hi, thank you for the suggestion, we are looking into it. If we implement this, it will take time, so we will be closing the issue as complete for now.
