### ISSUE TITLE
Tracking API doesn't return alternate tracking numbers

### ISSUE THREAD

**Issue by andreasblueher** [UPS-API/api-documentation#35]
Looking at this [link](https://www.ups.com/track?track=yes&trackNums=1ZV2391Y6821503452&loc=en_US&requester=ST/trackdetails) you can find under "View Details" an alternative tracking id. However if you use the tracking API this information is not returned although it's documented.

https://github.com/UPS-API/api-documentation/blob/71923ca98ad341a4ff7c8caaad6fcd32014f0571/Tracking.json#L244C15-L244C15

Can you please look into this? Am I doing something wrong? Thank you very much

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. The Tracking API now returns USPS only alternate tracking numbers.
