### ISSUE TITLE
Tracking API - tracking detail is missing GMT offsets

### ISSUE THREAD

**Issue by CycleMost** [UPS-API/api-documentation#38]
In the legacy XML tracking API, each activity had the local date and time, and also the GMT time and offsets, for example:

```
  <Activity>
    <ActivityLocation>
      <Address>
        <City>DUNLAP</City>
        <StateProvinceCode>TN</StateProvinceCode>
        <PostalCode>37327</PostalCode>
        <CountryCode>US</CountryCode>
      </Address>
      <Code>MN</Code>
      <Description>Side Door</Description>
      </ActivityLocation>
    <Date>20231130</Date>
    <Time>164340</Time>
    <GMTDate>2023-11-30</GMTDate>
    <GMTTime>21:43:40</GMTTime>
    <GMTOffset>-05:00</GMTOffset>
  </Activity>
```

In the new tracking API response, only the local date and time is given:

```
  {
    "location": {
      "address": {
        "city": "DUNLAP",
        "stateProvince": "TN",
        "countryCode": "US",
        "country": "US"
      },
      "slic": "3740"
    },
    "status": {
      "type": "D",
      "description": "DELIVERED ",
      "code": "FS",
      "statusCode": "011"
    },
    "date": "20231130",
    "time": "164340"
  }
```
QUESTION: How should we calculate the time zone of the activity date and time in the response json? Options:

1. Use the time zone of the city and state specified in activity.location.address
2. Use the package origin address

We have tried both of these in an attempt to match the dates and times given by the UPS tracking page, both with varying degress of success but results are not 100% accurate in either case. Is there an official business rule for how to determine the time zone of each activity? Or can we expect the GMT fields to be included in the API responses in the future?

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. The Tracking API now returns GMT information like gmtDate, gmtOffset, and gmtTime.
