### ISSUE TITLE
deliveryPhoto does not contain a photo

### ISSUE THREAD

**Issue by dijjit** [UPS-API/api-documentation#39]
We are trying to capture a Proof of Delivery (PoD) in our workflow via API - and a key element to this is the signature and the photo.
I see the deliveryPhoto object - which shows a photo string (which I expected to be a Base64 encoded image) - but the string "photo" is missing from my response;
```

   "deliveryInformation": {
                            "location": "Front door",
                            "deliveryPhoto": {
                                "photoCaptureInd": "Y",
                                "photoDispositionCode": "V",
                                "isNonPostalCodeCountry": false
                            }
                        },
```

How to get the photo? Given one was captured?

**Comment by jeffrey-cwj** [comment]
I think I met the same problem. How to get the pod(not the signature image) from "Tracking" API? or another API?

**Comment by hellcoderGIT** [comment]
Since switching to the YAML schemas the whole section of the DeliveryPhoto is now missing, signature is empty, online ups tracking page shows a delivery picture for my test shipments, how do we get this in the API now?

**Comment by chacham2** [comment]
I just called tech support about this and was told to send an email, which i just did. Our current system uses the old system, where the html page was included in the response.

Anyway, how are you all downloading the proof of delivery now? Can you even download it online?

**Comment by chacham2** [comment]
I got a reply from UPS Developer API Support:

> There are gaps between the OAuth RESTful Track API and XML/SOAP. These gaps have been identified and scheduled for testing and future release. The legacy Track API structure is similar but not the same as the Restful structure used with OAuth. Do not use the legacy track API developer guide to troubleshoot. 
>  
> Track Details
> 
> - Alternate tracking numbers (USPS only)
> - GMT information 
> - Milestones
> - Reference number
> - Direct to Retail (D2R), Retail to Retail (R2R) 
> - Delivery Signature (Signature Required and Adult Signature Required) 
> 
>  
> Release date: TBD
> 
> ReceivedBy 
> Package Dimensions
> HTML Proof of Delivery document
> Track by Reference number
> 
> Not currently supported: 
> 
> Barcode (BCDN)
> Delivery Photo 

When i asked what to do about the proof of delivery and if i should just continue using the old system:

>Yes, If you are comfortable using the XML API as of now you can use that until the releases are done for the new OAuth RESTful Track API.

So, i guess we'll continue to use the old system. For anyone else looking at what to do, [Legacy UPS Developer Kit](https://www.ups.com/upsdeveloperkit) says: 

>By June 2023, UPS will no longer issue new API access keys.

Being that date has passed, if you don't have an access key already, you might be out of luck. But even then, the [developer kit](https://developer.ups.com/) says:

> Beginning June 3, 2024, access keys will no longer be supported for authentication to any UPS APIs. 

So, it's only good for a short while longer, in any case. I really hope they finish implementing by then.

**Comment by jeffrey-cwj** [comment]
Add this {"returnPOD": "true"} to query params.

**Comment by ipavkovic** [comment]
@chacham2 is the content good enough for your purposes? I struggle a bit, see #76

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. The Track API does not return the delivery photo. The deliveryPhoto object in the Track API is to show if a photo exists.

**Comment by chacham2** [comment]
> The deliveryPhoto object in the Track API is to show if a photo exists.

But how do you get the photo?
