### ISSUE TITLE
There is only one AddressLine in Address tag Container 

### ISSUE THREAD

**Issue by shermantao** [UPS-API/api-documentation#4]
![image](https://github.com/UPS-API/api-documentation/assets/6101212/07759f28-6feb-4475-880b-4ae1aa3ed4b3)
I have a problem when debugging Shipping API. There is only one field "AddressLine" in the Address line of both Shipper Container and ShipTo Container. But in general, aren't there AddressLine1, AddressLine2, and AddressLine3? Is the system now upgraded so that only one address line field is left?

**Comment by chuntoulee** [comment]
![image](https://github.com/UPS-API/api-documentation/assets/111137867/a5dd6c55-0cf6-41a9-b0a5-9e31866fa7be)

**Comment by chuntoulee** [comment]
We accept an array of up to 3 occurrences of AddressLine. New documentation for Ship/Rate APIs was deployed on the portal and we will publish these updates to GitHub as well shortly.  

![image](https://github.com/UPS-API/api-documentation/assets/111137867/363358eb-9c55-44c2-8549-b26ee3a02a88)

**Comment by chuntoulee** [comment]
GitHub updates are also in place now.

**Comment by shermantao** [comment]
Great, solved my problem. Thank you
