### ISSUE TITLE
Tracking API has wrong endpoint

### ISSUE THREAD

**Issue by froodware** [UPS-API/api-documentation#40]
The right one appears to be **/api/track/v1/details/**

**Comment by florentpln** [comment]
+1, it is unclear why url did change on this commit?
https://github.com/UPS-API/api-documentation/commit/69c8f7d389a67f2235b556266513bed23c4286b7?diff=unified&w=1

**Comment by hellcoderGIT** [comment]
just stumbled over this too, track api did not work as the new endpoint 
 "/trackservice/tracking/v1/details/{inquiryNumber}"  is not available.
 
Rather inconvenient as that means we can't use the current .json schema for client code generation.
Ist there another url that provides the openapi json for the relevant CIE/Production version?

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have updated the repo with new YAML files.
