### ISSUE TITLE
Documentation is missing informations

### ISSUE THREAD

**Issue by IvanBossioP** [UPS-API/api-documentation#41]
I am trying to work with the UPS Track Alert API and I need to know what the event payload looks like. The current documentation shows how to set up the URL for receiving events but it doesn't give any detail about the format of the event data sent by the API. Since testing this requires creating a real shipment, it's not feasible for me right now. Can you provide an example of the event payload or update the documentation to include this information?

**Comment by UPSRahul** [comment]
Hi thank you for the comment. Our request schema for the call-back event is:
{
  "trackingNumber": "1ZXXXXXXXXXXXXXXXXX",
  "localActivityDate": "20240112",
  "localActivityTime": "154207",
  "activityLocation": {
    "city": "Atlanta",
    "stateProvince": "GA",
    "postalCode": "",
    "country": "US"
  },
  "activityStatus": {
    "type": "I",
    "code": "OR",
    "description": "On the Way"
  },
  "scheduledDeliveryDate": "20240118",
  "actualDeliveryDate": "",
  "actualDeliveryTime": "",
  "gmtActivityDate": "20240112",
  "gmtActivityTime": "204207",
  "deliveryStartTime": "",
  "deliveryEndTime": "",
  "deliveryTimeDescription": "",
  "deliveryPhoto": ""                 
}

**Comment by mowny** [comment]
> Agree. Providing testing APIs to trigger shipment status changes in CIE is also important, as it's not feasible to test by using real tracking numbers and wait for status change every time.

Related: _Is_ there a testing environment for the new API, or is there only prod now? I do not like to test in prod.
