### ISSUE TITLE
TransactionIdentifier is missing in Shipping schema.

### ISSUE THREAD

**Issue by florentpln** [UPS-API/api-documentation#47]
TransactionIdentifier field is not documented in Shipping.yaml, whereas it is returned by shipment creation API on location : ShipmentResponse -> Response -> TransactionReference -> TransactionIdentifier

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. In your requests, are you passing a TransactionIdentifier?

**Comment by UPSRahul** [comment]
Hi, we are closing this issue as completed. If there are any additional questions, please create a new issue.
