### ISSUE TITLE
Why does /track/v1/details/{inquiryNumber} have error 207?

### ISSUE THREAD

**Issue by chacham2** [UPS-API/api-documentation#49]
Tracking.yaml under "/track/v1/details/{inquiryNumber}" error codes has '207':  description: Tracking Information not found for all inquiry numbers

Being it's a request for just one number, isn't that the same as '404': description: Tracking number information not found

**Comment by Drodarious** [comment]
If you are sending a request to exactly "/track/v1/details/{inquiryNumber}"; and it is common knowledge that UPS tracking numbers do not contain non-alphnumeric characters like brackets, then it makes sense that the inclusion of any non-alphnumeric character would be inferred as an attempt to provide an array. In this case, an improperly formatted one.

**Comment by chacham2** [comment]
Sorry. I meant that was the heading in Tracking.yaml for the paragraph that includes that description. Not that it was the query being sent.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment and patience. We have updated the specs to resolve this issue.
