### ISSUE TITLE
Paperless Documents API: Incorrect types

### ISSUE THREAD

**Issue by david-szabo97** [UPS-API/api-documentation#5]
### `UploadRequest.UserCreatedForm` supposed to be an `array`, yet it's defined as an `object`.

The correct type would be something like this:
```json
"UserCreatedForm": {
  "type": "array",
  "maxItems": 13,
  "items": {
    "$ref": "#/components/schemas/UploadRequest_UserCreatedForm"
  }
}
```

### `UploadResponse_FormsHistoryDocumentID.DocumentID` is returned as an `object` when only a single item is present, otherwise `array`

This property should always be an `array` in the response. This issue is present at other UPS APIs as well.

**Comment by UPSRahulBhatnagar** [comment]
Hi, thank you for your comment. Please refer to: https://github.com/UPS-API/api-documentation/issues/3#issuecomment-1796167729. We will keep the linked thread open for discussion.
