### ISSUE TITLE
OAuthClientCredentials API: server URLs lead to http 404

### ISSUE THREAD

**Issue by AlexAtPeerless** [UPS-API/api-documentation#50]
In OAuthClientCredentials.yaml the server URLs appear wrong, as once combined with the path it leads to:

https://wwwcie.ups.com/api/security/v1/oauth/token

For which I get http 404 not found...

Online tester [https://developer.ups.com/api/reference?loc=en_US#operation/CreateToken](url) leads to:

https://wwwcie.ups.com/security/v1/oauth/token

This one does work...

Please fix or explain how in the world this is supposed to be right...

**Comment by chacham2** [comment]
I just tested and got a good response. Here's what i sent:

Endpoint: https://onlinetools.ups.com/security/v1/oauth/token 
Method: POST
(Content Header) Content-Type: application/x-www-form-urlencoded
Content: grant_type=client_credentials
(Header) Authorization: Basic ...

**Comment by AlexAtPeerless** [comment]
@chacham2 Of course if you correct the url it's going to work.
What I'm reporting here is that the schema currently available for download contains a different url that does not work as it adds the /api/ part:

openapi: 3.0.3
info:
  title: OAuth Client Credentials API
  version: ''
servers:
- url: https://wwwcie.ups.com**/api/**
  description: Customer Integration Environment for Client Credentials
- url: https://onlinetools.ups.com**/api/**
  description: Production for Client Credentials
...
So you end up with https://wwwcie.ups.com/api/security/v1/oauth/token, not https://wwwcie.ups.com/security/v1/oauth/token which you tested.

**Comment by abolabo** [comment]
https://wwwcie.ups.com/api/security/v1/oauth/token returns 404
https://wwwcie.ups.com/security/v1/oauth/token is correct url

**Comment by UPSRahul** [comment]
Hi, thank you for your comment and patience. We have updated the specs to resolve this issue.
