### ISSUE TITLE
Attempting to view Alert results in 404

### ISSUE THREAD

**Issue by Drodarious** [UPS-API/api-documentation#51]
![ups2](https://github.com/UPS-API/api-documentation/assets/4616519/d7d3c866-c5cd-4df4-b225-ed5a4ff4bda3)

I am trying to debug an issue and would like to determine if the alert is relevant, but attempting to view the alert results in a 404.

**Repro Steps:**
Login to developer.ups.com with an account that has an active alert
click "Service Alerts" found on the right side of the main header

**Expected Result:** Information detailing the alert

**Actual Result:** HTTP ERROR 404

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. This issue has been resolved. Just a heads up, these service alerts are not user-specific alerts, they relate to UPS as a whole.
