### ISSUE TITLE
Locator API: Wrong response definition (DropLocation)?

### ISSUE THREAD

**Issue by florianschieder** [UPS-API/api-documentation#53]
Hello there,
we are currently migrating to the new REST API.
I think there is a mistake regarding the `DropLocation` within the `LocatorRequestResponse`:
- https://github.com/UPS-API/api-documentation/blob/main/Locator.yaml#L1267
- https://github.com/UPS-API/api-documentation/blob/main/Locator.yaml#L1362
Previously, there was a list of `DropLocation`s in the old XML API. The API documentation states there is only one `DropLocation` entity which leads to wrong results for `swagger-codegen`-based model structures as far I interpret the deserialization.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment and patience. We have updated the specs to resolve this issue.
