### ISSUE TITLE
Shipping API ShipTo address and Address Validation API

### ISSUE THREAD

**Issue by mguoPA** [UPS-API/api-documentation#55]
Hi, we have integrated SHIP API in our system and we have recevied extra charge because of address correction. 
 
In the shipto "AddressLine" field, if I sent data {"Address":"AddressLine":["attn: John Doe", "9999 CHARLIE DANIELS PARKWAY",]}  etc. Your system recorded the address as "attn: John Doe 9999 CHARLIE ". Could you advise why you don't take the full addressline in your system as API says first two address line will be printed on label and on label it actually prints the full address but not recorded in your system? 

I used Address validation API to validate the address, but sometimes the result is not right. For example, it will remove the SUITE  Number from the addressline and I have one customer with address "STE103/104" will be "STE 107A" eventually. 

Any ideas how can avoid extra charge by UPS for address correction? Thank you.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. Please use the ShipTo.AttentionName field for your "John Doe" example. For the second question please reach out to the UPS help desk:  https://developer.ups.com/contactus
