### ISSUE TITLE
Shipping API Missing ShipAcceptRequest and ShipConfirmRequest

### ISSUE THREAD

**Issue by mattp773** [UPS-API/api-documentation#56]
In previous iterations, there were ShipAcceptRequest and ShipConfirmRequest (as well as their respective response) types. These are mentioned in various descriptions of items defined in the YAML, but the actual types are not defined anywhere. See attached type definitions from legacy developer kit xml schema.
[ShipConfirmAcceptTypes.zip](https://github.com/UPS-API/api-documentation/files/14485868/ShipConfirmAcceptTypes.zip)

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. Two phase shipments, a ship confirm followed by a ship accept, are not supported in the new REST format. Only single phase ShipmentRequest are supported.
