### ISSUE TITLE
Paperlessdocument file encoding

### ISSUE THREAD

**Issue by ochnygosch** [UPS-API/api-documentation#59]
Hi, 
I'm missing some information about the encoding of the files to upload. 
In the provided examples for the paperlessdocuments/{version}/upload endpoint the field UserCreatedFormFile looks like it is base64 encoded, but I couldn't find any information about that in the documentation.

So: Is this field meant to be base64 encoded and if so the documentation should reflect that.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment and patience. We have updated the specs to resolve this issue.
