### ISSUE TITLE
Shipping API required properties missing

### ISSUE THREAD

**Issue by david-szabo97** [UPS-API/api-documentation#6]
So far, we have encountered the following properties marked as required but not returned in the response in all circumstances:

- `PackageResults_ShippingLabel.GraphicImagePart`
- `ShipmentResults_Form.Description`
- `ShipmentResults_Form.Code`

**Comment by chuntoulee** [comment]
Thank you for bringing this concern to our attention.  Our technical team is looking into it and will provide a more substantive response shortly.

**Comment by UPSRahulBhatnagar** [comment]
Hi, our team has taken a look and come to the following conclusion.

**- PackageResults_ShippingLabel.GraphicImagePart**: Thank you, we have fixed this.
**- ShipmentResults_Form.Description:** The description and code are always required when the form element is returned; however, the form element is not required to be returned in the ShipmentResults.
**- ShipmentResults_Form.Code:** The description and code are always required when the form element is returned; however, the form element is not required to be returned in the ShipmentResults.
