### ISSUE TITLE
PaperlessDocuments - upload multiple documents, response only provide one document id

### ISSUE THREAD

**Issue by ipavkovic** [UPS-API/api-documentation#60]
In current SOAP UPS service the response from UPS returns list of document id, for every document in the upload request.

The REST response only provides a single document Id, even on uploading multiple documents in one request as defined here: https://developer.ups.com/api/reference?loc=en_US#operation/Upload!c=200&path=UploadResponse/FormsHistoryDocumentID/DocumentID&t=response

is this done on purpose?

**Comment by sliwinski-m-1** [comment]
It looks like the specification does not match real responses returned by REST Paperless API. An array is returned even for single documentId.
![image](https://github.com/UPS-API/api-documentation/assets/62235873/45757bdb-321a-47b1-b9f1-8d76c08c7f82)

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. Is your inquiry regarding the Paperless API documentation or API functionality?

**Comment by ipavkovic** [comment]
@UPSRahul it turns out to be an error in the api-documentation, see https://github.com/UPS-API/api-documentation/blob/main/Paperless.yaml#L594 .
