### ISSUE TITLE
Rating API: Shoptimeintransit does not work for non domestic

### ISSUE THREAD

**Issue by hobbefant** [UPS-API/api-documentation#64]
As soon as I change the addresses to be different countries I get the following error:

```
{
    "response": {
        "errors": [
            {
                "code": "111549",
                "message": "Invalid Shipment Contents Value."
            }
        ]
    }
}
```

Rate is working, shop is working, but Shoptimeintransit and ratetimeintransit are not.

If anybody has a working example I would really appreciate it.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. The field "Shipment.InvoiceLineTotal" is required for international shipments with "ratetimeintransit" and "shoptimeintransit".
