### ISSUE TITLE
Shipment: undefined parameter `ItemizedChargesRequestedIndicator`

### ISSUE THREAD

**Issue by xerc** [UPS-API/api-documentation#65]
https://github.com/UPS-API/api-documentation/blob/1646e7cfa63a4cb462625a476c94adcfb2d744f9/Shipping.yaml#L169
https://github.com/UPS-API/api-documentation/blob/1646e7cfa63a4cb462625a476c94adcfb2d744f9/Shipping.yaml#L560

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have updated the specs to resolve this issue - the field is no longer needed so we removed from the example requests.
