### ISSUE TITLE
Shipping endpoint missing International Form

### ISSUE THREAD

**Issue by elidrissidev** [UPS-API/api-documentation#69]
When shipping to destinations that support paperless invoice, the REST API does not seem to include the `Forms` field under `ShipmentResults` using version `v2108` of the API. The same request made with the old XML API includes the field. Is there another condition for returning the international form in the new API?

**Comment by UPSRahul** [comment]
Hi, we are unable to replicate this concern. For further help, please contact the UPS Help Desk: https://developer.ups.com/contactus
