### ISSUE TITLE
Shipment notifications seemingly not supported for in JSON API?  Say what?!

### ISSUE THREAD

**Issue by nightcoding2021** [UPS-API/api-documentation#70]
For years I've populated buyer email notifications via <PackageServiceOptions><Notification> in the XML API.  This triggers an immediate email to the package recipients email address.

Inexplicably, the same container in JSON references this is only for "Receiver Return Notification" (whatever that is).  If I include the container anyway, an erroneous error message _{"code":"9120000","message":"Ship web service is currently unavailable."_ is returned.

![image](https://github.com/UPS-API/api-documentation/assets/85417724/9a0b99ee-77aa-48fd-a337-5c623cecff3d)

It doesn't appear UPS are bothering to contribute to these threads, but should they do so, can someone let me know how this extremely basic function - shipment notifications - can be issued as before, and indeed the same as any other carrier in the globe.

Looking increasingly obvious this JSON API is a guaranteed downgrade - losing functionality.  It would appear nowhere near something they should be going live with.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. The screenshot shown above is for package notifications tied to return shipments. Please reference Shipment Service Options -> Notifications for Shipment Notifications. We will look into updating the error message to be clearer.

**Comment by UPSRahul** [comment]
Hi, we are closing this issue as completed. If there are any additional questions, please create a new issue.
