### ISSUE TITLE
Account for shipment creation with billing to receiver or third party  

### ISSUE THREAD

**Issue by mpribela** [UPS-API/api-documentation#73]
Hello,

I would like to test a shipment creation with _ShipmentCharge_ set to _BillReciever_ and _BillThirdParty_. But the request always fails on an invalid account number.
Could you please provide me with a testing account number to test the functionality?

**Comment by ipavkovic** [comment]
we needed to add a valid account number in the app settings developer.ups.com/apps/<your-app-name>

**Comment by UPSRahul** [comment]
> we needed to add a valid account number in the app settings developer.ups.com/apps/ <img alt="Bildschirmfoto 2024-04-03 um 09 36 38" width="1152" src="https://private-user-images.githubusercontent.com/5860340/319086458-3e44d106-b171-4123-ad4a-f85228546602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzYwNDksIm5iZiI6MTcxMjE3NTc0OSwicGF0aCI6Ii81ODYwMzQwLzMxOTA4NjQ1OC0zZTQ0ZDEwNi1iMTcxLTQxMjMtYWQ0YS1mODUyMjg1NDY2MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMjAyMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc3MDZkN2VhZTRlMDE4M2ZhNzk3ZjljODkzMGI2YzEzMTc5MWRlOGRhNTc3NDVlMmE4YWNhOTJkYzFjZTBiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y2KmEqDE9qdtuiKrEOAwBqZ-IK1pZ4SD9pg8nOVi-NQ">

Hi, thank you for your comment. The billing account number in the developer portal is only used to pay for monetized APIs (like TrackAlert).

**Comment by UPSRahul** [comment]
> we needed to add a valid account number in the app settings developer.ups.com/apps/ <img alt="Bildschirmfoto 2024-04-03 um 09 36 38" width="1152" src="https://private-user-images.githubusercontent.com/5860340/319086458-3e44d106-b171-4123-ad4a-f85228546602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzYwNDksIm5iZiI6MTcxMjE3NTc0OSwicGF0aCI6Ii81ODYwMzQwLzMxOTA4NjQ1OC0zZTQ0ZDEwNi1iMTcxLTQxMjMtYWQ0YS1mODUyMjg1NDY2MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMjAyMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc3MDZkN2VhZTRlMDE4M2ZhNzk3ZjljODkzMGI2YzEzMTc5MWRlOGRhNTc3NDVlMmE4YWNhOTJkYzFjZTBiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y2KmEqDE9qdtuiKrEOAwBqZ-IK1pZ4SD9pg8nOVi-NQ">

Hi, thank you for your comment. The billing account number in the developer portal is only used to pay for monetized APIs (like TrackAlert).

**Comment by UPSRahul** [comment]
> Hello,
> 
> I would like to test a shipment creation with _ShipmentCharge_ set to _BillReciever_ and _BillThirdParty_. But the request always fails on an invalid account number. Could you please provide me with a testing account number to test the functionality?

Hi, thank you for your comment. These actions imply relationships between the shipper and the payer of charges. This requires explicit setup from account number to account number. Please call your account representative for this.
