### ISSUE TITLE
Rates associated with shipper number are probably not sent correctly 

### ISSUE THREAD

**Issue by mpribela** [UPS-API/api-documentation#74]
Hello,

When I try rate or shipment request with _CustomerClassification_ set to _00_ (Rates associated with shipper number) I always receive null fees (itemized charges) in objects:
```
RateResponse.RatedShipment[].NegotiatedRateCharges.ItemizedCharges[]
RateResponse.RatedShipment[].RatedPackage[].NegotiatedCharges
```

```{
  "RateResponse": {
    "RatedShipment": [
      {
        "NegotiatedRateCharges": {
          "ItemizedCharges": null,
          "TaxCharges": null,
          "TotalCharge": {
            "CurrencyCode": "USD",
            "MonetaryValue": 14.58
          },
          "TotalChargesWithTaxes": null
        },
        "RatedPackage": [
          {
            "NegotiatedCharges": null
          }
        ]
      }
    ]
  }
}
```

According to the documentation, itemized charges should be returned with contract-only shipments.
Could you provide me with more information when those fields are filled?

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. When making these requests, are you using the CIE or Onlinetools (production) environment?

**Comment by mpribela** [comment]
It is the CIE environment.

**Comment by UPSRahul** [comment]
Hi, the CIE environment uses mock information and is meant to test the interface. Please use the onlinetools (production) environment to see if this issue is resolved.

**Comment by UPSRahul** [comment]
Hi, in this situation, please contact your UPS partner representative to aid in the process and have you certified.
