### ISSUE TITLE
TrackingResponse with parameter returnPOD=true delivers invalid HTML

### ISSUE THREAD

**Issue by ipavkovic** [UPS-API/api-documentation#76]
calling tracking api with returnPOD=true returns DeliveryInformation.pod.content with the following base64 decoded string (sensitive informations XXXed out)

```
<!DOCTYPE html>
<html>
    <title>Delivery Notification</title>

    <head>
        <mets charset="UTF-8"></mets>
        <style>
            .centered-div {

            text-indent: 50px;
            }
        </style>
    </head>

    <body>
        <h1>Delivery Notification</h1>
        <div>Dear Customer,</div>

        <p>This is in response to your request for delivery information concerning the shipment listed below.</p>
        <div class="centered-div">Tracking Number : XXX</div>
        <div class="centered-div">Reference Number(s) : XXX, XXX</div>
        <div class="centered-div">Service Type : UPS Express Saver®</span></div>
    <div class="centered-div">Package Weight : XXX</div>
    <div class="centered-div">Shipped or Billed on : XXX</div>
    <div class="centered-div">Delivered on : XXX</div>
    <div class="centered-div">Delivered to : Empfänger</div>
    <p>Thank you for giving us this opportunity to serve you</p>
    <div>Sincerely,</div>
    <div>United Parcel Service</div>
    <br></br>
    <div> Tracking results provided by UPS: Apr 03, 2024 06:41 AM Eastern Time (USA)</span></div>

        </body>

        </html>
```
- `<mets` is no valid tag 
- multiple closing `</span>` without opening spans
- compared to XML SOAP response no img src tags are found like  `<IMG src="./ups_logo.gif" ALT="UPS Logo">`, `<IMG src="./ups_banner.gif" ALT="UPS Banner">` and `<IMG src="pod_XXX.gif" ALT="Signature">`
- also, reading the texts `Delivery Notification` and `This is in response to your request for delivery information concerning the shipment listed below.` I am not sure if this is a proof of delivery at all

**Comment by hellcoderGIT** [comment]
haha, at this point it's maybe easier to just create this "POD" (html) yourself from the tracking data.
The whole topic is such a joke. If UPS doesn't have a proper POD (who could blame them), but EU law requires it, it should be enough for us "customers" to have the tracking number, for the rest, authorities should deal with the carriers directly.

**Comment by chacham2** [comment]
> just create this "POD" (html) yourself from the tracking data.

I was wondering that too. But, the point is, should we get audited, we'll need UPS to stand behind us on that document. Using anything other than what they provide might hinder that.

**Comment by chacham2** [comment]
> * `<mets` is no valid tag
> * multiple closing `</span>` without opening spans

If the browser opens it and UPS will stand behind it. This should be good enough. Though, we do need to look to UPS to correct it to the standard.

> * compared to XML SOAP response no img src tags are found like  `<IMG src="./ups_logo.gif" ALT="UPS Logo">`, `<IMG src="./ups_banner.gif" ALT="UPS Banner">` and `<IMG src="pod_XXX.gif" ALT="Signature">`

That's more interesting, because they do not supply the logo's in the return; they just refer to them. Will they do the same here? I doubt they want to send the gif in every response.

As for the signature, you have it separately (assuming it is implemented). 

> * also, reading the texts `Delivery Notification` and `This is in response to your request for delivery information concerning the shipment listed below.` I am not sure if this is a proof of delivery at all

Hmm...

**Comment by ipavkovic** [comment]
> 
> As for the signature, you have it separately (assuming it is implemented).
> 
> > * also, reading the texts `Delivery Notification` and `This is in response to your request for delivery information concerning the shipment listed below.` I am not sure if this is a proof of delivery at all
> 
> Hmm...
with soap message, both having pod as html and signature image attached, and together with two logos from ups web site, we could produce a lookalike proof of delivery document as provided by ups themselves

**Comment by chacham2** [comment]
>we could produce a lookalike proof of delivery document as provided by ups themselves

I just went to the website. Here's the PoD they give:

![image](https://github.com/UPS-API/api-documentation/assets/14092279/fe720a89-d5b6-440e-ace7-dd38af248468)

If i choose the "Print this page" option:

![image](https://github.com/UPS-API/api-documentation/assets/14092279/1381663f-3c7d-49c0-aa99-b673b2f43e14)

So, based on what UPS provides now, i would say images are no longer used as part of the PoD.

**Comment by ataylorkato** [comment]
@UPSRahul @UPSCadeCreech Can we get some confirmation that it's intended that signature images are no longer returned, despite specifying both `returnSignature=true` and `returnPOD=true`?

**Comment by UPSRahul** [comment]
> @UPSRahul @UPSCadeCreech Can we get some confirmation that it's intended that signature images are no longer returned, despite specifying both `returnSignature=true` and `returnPOD=true`?

Hi, please reference issue #57.

**Comment by UPSRahul** [comment]
Hi, thank you for your comment. We have updated the POD HTML.
