### ISSUE TITLE
API Rate Limits

### ISSUE THREAD

**Issue by jimpeters** [UPS-API/api-documentation#8]
Are the Rate Limits published for the REST API?  I do not see any response headers when I hit a 429 and am just curious what the parameters are.  I have reviewed the documentation and FAQ and cannot find any specifics.

Thanks!

**Comment by chuntoulee** [comment]
Thank you for bringing this question to our attention.  

If you received a 429 error and would like rate limit evaluated for your usage, please send your client id/ access key, API being used and the rate limit you require to meet your business needs to [uoltects@ups.com](mailto:uoltects@ups.com).
