### ISSUE TITLE
Shipping: no need to `base64` if `ImageFormat` is `*PL`

### ISSUE THREAD

**Issue by xerc** [UPS-API/api-documentation#87]
`[\r\n]` => `null`
`^\s+|\s+$` => `null`

& new variable-name ?!

btw/ not always hints to (smaller size) `PNG` @ `Shipping API`

**Comment by UPSRahul** [comment]
Hi, would you mind providing a bit more context behind this inquiry?

**Comment by xerc** [comment]
remove the line-breaks and emtpy lines in start & end if the `*PL` - there will be no need to `base64encode` anymore
will result in less cpu-cycles (on both sides) and less trafic/better gzip

**Comment by UPSRahul** [comment]
Hi, we appreciate the suggestion, but at this time, we will not be able to update this due to the large number of customer integrations we currently have and the potential for issues to arise.
