### ISSUE TITLE
Re-using refresh tokens

### ISSUE THREAD

**Issue by dionysio** [UPS-API/api-documentation#90]
Hi UPS team,

once a refresh token is used for the refresh operation successfully, is it considered expired?

**Comment by ipavkovic** [comment]
@dionysio https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/ states

> If everything checks out, the service can generate an access token
> and respond. The server may issue a new refresh token in the response, 
> but if the response does not include a new refresh token, the client 
> assumes the existing refresh token will still be valid.

**Comment by UPSRahul** [comment]
Hi, thank you for your comments. Once a refresh token is used, a new refresh token will be sent, and the used refresh token cannot be used again.
